version: '3.8'
services:
  sublimegateway:
    image: sublimegateway
    build:
      context: .
      dockerfile: SublimeGateway/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
